/*
 * This file is generated by jOOQ.
 */
package com.tinge.nebula.entity.rule_dict;


import com.tinge.nebula.entity.rule_dict.tables.RuleWord;
import com.tinge.nebula.entity.rule_dict.tables.SimilarWord;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>rule_dict</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PRIMARY_KEY_8 = Indexes0.PRIMARY_KEY_8;
    public static final Index PRIMARY_KEY_2 = Indexes0.PRIMARY_KEY_2;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PRIMARY_KEY_8 = Internal.createIndex("PRIMARY_KEY_8", RuleWord.RULE_WORD, new OrderField[] { RuleWord.RULE_WORD.ID }, true);
        public static Index PRIMARY_KEY_2 = Internal.createIndex("PRIMARY_KEY_2", SimilarWord.SIMILAR_WORD, new OrderField[] { SimilarWord.SIMILAR_WORD.ID }, true);
    }
}
