/*
 * This file is generated by jOOQ.
 */
package com.tinge.nebula.entity.rule_dict;


import com.tinge.nebula.entity.rule_dict.tables.RuleWord;
import com.tinge.nebula.entity.rule_dict.tables.SimilarWord;
import com.tinge.nebula.entity.rule_dict.tables.records.RuleWordRecord;
import com.tinge.nebula.entity.rule_dict.tables.records.SimilarWordRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>rule_dict</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<RuleWordRecord, Long> IDENTITY_RULE_WORD = Identities0.IDENTITY_RULE_WORD;
    public static final Identity<SimilarWordRecord, Long> IDENTITY_SIMILAR_WORD = Identities0.IDENTITY_SIMILAR_WORD;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<RuleWordRecord> CONSTRAINT_8 = UniqueKeys0.CONSTRAINT_8;
    public static final UniqueKey<SimilarWordRecord> CONSTRAINT_2 = UniqueKeys0.CONSTRAINT_2;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<RuleWordRecord, Long> IDENTITY_RULE_WORD = Internal.createIdentity(RuleWord.RULE_WORD, RuleWord.RULE_WORD.ID);
        public static Identity<SimilarWordRecord, Long> IDENTITY_SIMILAR_WORD = Internal.createIdentity(SimilarWord.SIMILAR_WORD, SimilarWord.SIMILAR_WORD.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<RuleWordRecord> CONSTRAINT_8 = Internal.createUniqueKey(RuleWord.RULE_WORD, "CONSTRAINT_8", RuleWord.RULE_WORD.ID);
        public static final UniqueKey<SimilarWordRecord> CONSTRAINT_2 = Internal.createUniqueKey(SimilarWord.SIMILAR_WORD, "CONSTRAINT_2", SimilarWord.SIMILAR_WORD.ID);
    }
}
