/*
 * This file is generated by jOOQ.
 */
package com.tinge.nebula.entity.rule_dict;


import com.tinge.nebula.entity.DefaultCatalog;
import com.tinge.nebula.entity.rule_dict.tables.RuleWord;
import com.tinge.nebula.entity.rule_dict.tables.SimilarWord;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RuleDict extends SchemaImpl {

    private static final long serialVersionUID = -1764307453;

    /**
     * The reference instance of <code>rule_dict</code>
     */
    public static final RuleDict RULE_DICT = new RuleDict();

    /**
     * The table <code>rule_dict.rule_word</code>.
     */
    public final RuleWord RULE_WORD = com.tinge.nebula.entity.rule_dict.tables.RuleWord.RULE_WORD;

    /**
     * The table <code>rule_dict.similar_word</code>.
     */
    public final SimilarWord SIMILAR_WORD = com.tinge.nebula.entity.rule_dict.tables.SimilarWord.SIMILAR_WORD;

    /**
     * No further instances allowed
     */
    private RuleDict() {
        super("rule_dict", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            RuleWord.RULE_WORD,
            SimilarWord.SIMILAR_WORD);
    }
}
