/*
 * This file is generated by jOOQ.
 */
package com.tinge.nebula.entity.rule_dict;


import com.tinge.nebula.entity.rule_dict.tables.RuleWord;
import com.tinge.nebula.entity.rule_dict.tables.SimilarWord;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in rule_dict
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>rule_dict.rule_word</code>.
     */
    public static final RuleWord RULE_WORD = com.tinge.nebula.entity.rule_dict.tables.RuleWord.RULE_WORD;

    /**
     * The table <code>rule_dict.similar_word</code>.
     */
    public static final SimilarWord SIMILAR_WORD = com.tinge.nebula.entity.rule_dict.tables.SimilarWord.SIMILAR_WORD;
}
