/*
 * This file is generated by jOOQ.
 */
package com.tinge.nebula.entity.rule_dict.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RuleWord implements Serializable {

    private static final long serialVersionUID = -1474437673;

    private Long      id;
    private Integer   source;
    private Long      operatorId;
    private String    word;
    private Integer   wordType;
    private Integer   matchType;
    private Integer   entityType;
    private String    excludeWords;
    private String    excludeUsers;
    private String    excludeCustomers;
    private String    industries;
    private Integer   grade;
    private Integer   status;
    private String    remark;
    private String    riskTag;
    private String    extraData;
    private Timestamp createTime;
    private Timestamp modifyTime;

    public RuleWord() {}

    public RuleWord(RuleWord value) {
        this.id = value.id;
        this.source = value.source;
        this.operatorId = value.operatorId;
        this.word = value.word;
        this.wordType = value.wordType;
        this.matchType = value.matchType;
        this.entityType = value.entityType;
        this.excludeWords = value.excludeWords;
        this.excludeUsers = value.excludeUsers;
        this.excludeCustomers = value.excludeCustomers;
        this.industries = value.industries;
        this.grade = value.grade;
        this.status = value.status;
        this.remark = value.remark;
        this.riskTag = value.riskTag;
        this.extraData = value.extraData;
        this.createTime = value.createTime;
        this.modifyTime = value.modifyTime;
    }

    public RuleWord(
        Long      id,
        Integer   source,
        Long      operatorId,
        String    word,
        Integer   wordType,
        Integer   matchType,
        Integer   entityType,
        String    excludeWords,
        String    excludeUsers,
        String    excludeCustomers,
        String    industries,
        Integer   grade,
        Integer   status,
        String    remark,
        String    riskTag,
        String    extraData,
        Timestamp createTime,
        Timestamp modifyTime
    ) {
        this.id = id;
        this.source = source;
        this.operatorId = operatorId;
        this.word = word;
        this.wordType = wordType;
        this.matchType = matchType;
        this.entityType = entityType;
        this.excludeWords = excludeWords;
        this.excludeUsers = excludeUsers;
        this.excludeCustomers = excludeCustomers;
        this.industries = industries;
        this.grade = grade;
        this.status = status;
        this.remark = remark;
        this.riskTag = riskTag;
        this.extraData = extraData;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getSource() {
        return this.source;
    }

    public void setSource(Integer source) {
        this.source = source;
    }

    public Long getOperatorId() {
        return this.operatorId;
    }

    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    public String getWord() {
        return this.word;
    }

    public void setWord(String word) {
        this.word = word;
    }

    public Integer getWordType() {
        return this.wordType;
    }

    public void setWordType(Integer wordType) {
        this.wordType = wordType;
    }

    public Integer getMatchType() {
        return this.matchType;
    }

    public void setMatchType(Integer matchType) {
        this.matchType = matchType;
    }

    public Integer getEntityType() {
        return this.entityType;
    }

    public void setEntityType(Integer entityType) {
        this.entityType = entityType;
    }

    public String getExcludeWords() {
        return this.excludeWords;
    }

    public void setExcludeWords(String excludeWords) {
        this.excludeWords = excludeWords;
    }

    public String getExcludeUsers() {
        return this.excludeUsers;
    }

    public void setExcludeUsers(String excludeUsers) {
        this.excludeUsers = excludeUsers;
    }

    public String getExcludeCustomers() {
        return this.excludeCustomers;
    }

    public void setExcludeCustomers(String excludeCustomers) {
        this.excludeCustomers = excludeCustomers;
    }

    public String getIndustries() {
        return this.industries;
    }

    public void setIndustries(String industries) {
        this.industries = industries;
    }

    public Integer getGrade() {
        return this.grade;
    }

    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getRiskTag() {
        return this.riskTag;
    }

    public void setRiskTag(String riskTag) {
        this.riskTag = riskTag;
    }

    public String getExtraData() {
        return this.extraData;
    }

    public void setExtraData(String extraData) {
        this.extraData = extraData;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(Timestamp modifyTime) {
        this.modifyTime = modifyTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RuleWord (");

        sb.append(id);
        sb.append(", ").append(source);
        sb.append(", ").append(operatorId);
        sb.append(", ").append(word);
        sb.append(", ").append(wordType);
        sb.append(", ").append(matchType);
        sb.append(", ").append(entityType);
        sb.append(", ").append(excludeWords);
        sb.append(", ").append(excludeUsers);
        sb.append(", ").append(excludeCustomers);
        sb.append(", ").append(industries);
        sb.append(", ").append(grade);
        sb.append(", ").append(status);
        sb.append(", ").append(remark);
        sb.append(", ").append(riskTag);
        sb.append(", ").append(extraData);
        sb.append(", ").append(createTime);
        sb.append(", ").append(modifyTime);

        sb.append(")");
        return sb.toString();
    }
}
