/*
 * This file is generated by jOOQ.
 */
package com.tinge.nebula.entity.rule_dict.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SimilarWord implements Serializable {

    private static final long serialVersionUID = -742860937;

    private Long      id;
    private Long      operatorId;
    private Integer   source;
    private String    originalWord;
    private String    similarWord;
    private Integer   status;
    private String    remark;
    private String    extraData;
    private Timestamp createTime;
    private Timestamp modifyTime;

    public SimilarWord() {}

    public SimilarWord(SimilarWord value) {
        this.id = value.id;
        this.operatorId = value.operatorId;
        this.source = value.source;
        this.originalWord = value.originalWord;
        this.similarWord = value.similarWord;
        this.status = value.status;
        this.remark = value.remark;
        this.extraData = value.extraData;
        this.createTime = value.createTime;
        this.modifyTime = value.modifyTime;
    }

    public SimilarWord(
        Long      id,
        Long      operatorId,
        Integer   source,
        String    originalWord,
        String    similarWord,
        Integer   status,
        String    remark,
        String    extraData,
        Timestamp createTime,
        Timestamp modifyTime
    ) {
        this.id = id;
        this.operatorId = operatorId;
        this.source = source;
        this.originalWord = originalWord;
        this.similarWord = similarWord;
        this.status = status;
        this.remark = remark;
        this.extraData = extraData;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getOperatorId() {
        return this.operatorId;
    }

    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    public Integer getSource() {
        return this.source;
    }

    public void setSource(Integer source) {
        this.source = source;
    }

    public String getOriginalWord() {
        return this.originalWord;
    }

    public void setOriginalWord(String originalWord) {
        this.originalWord = originalWord;
    }

    public String getSimilarWord() {
        return this.similarWord;
    }

    public void setSimilarWord(String similarWord) {
        this.similarWord = similarWord;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getExtraData() {
        return this.extraData;
    }

    public void setExtraData(String extraData) {
        this.extraData = extraData;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(Timestamp modifyTime) {
        this.modifyTime = modifyTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SimilarWord (");

        sb.append(id);
        sb.append(", ").append(operatorId);
        sb.append(", ").append(source);
        sb.append(", ").append(originalWord);
        sb.append(", ").append(similarWord);
        sb.append(", ").append(status);
        sb.append(", ").append(remark);
        sb.append(", ").append(extraData);
        sb.append(", ").append(createTime);
        sb.append(", ").append(modifyTime);

        sb.append(")");
        return sb.toString();
    }
}
