/*
 * This file is generated by jOOQ.
 */
package com.tinge.nebula.entity.rule_dict.tables.records;


import com.tinge.nebula.entity.rule_dict.tables.SimilarWord;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SimilarWordRecord extends UpdatableRecordImpl<SimilarWordRecord> implements Record10<Long, Long, Integer, String, String, Integer, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -415105943;

    /**
     * Setter for <code>rule_dict.similar_word.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>rule_dict.similar_word.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>rule_dict.similar_word.operator_id</code>.
     */
    public void setOperatorId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>rule_dict.similar_word.operator_id</code>.
     */
    public Long getOperatorId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>rule_dict.similar_word.source</code>.
     */
    public void setSource(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>rule_dict.similar_word.source</code>.
     */
    public Integer getSource() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>rule_dict.similar_word.original_word</code>.
     */
    public void setOriginalWord(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rule_dict.similar_word.original_word</code>.
     */
    public String getOriginalWord() {
        return (String) get(3);
    }

    /**
     * Setter for <code>rule_dict.similar_word.similar_word</code>.
     */
    public void setSimilarWord(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>rule_dict.similar_word.similar_word</code>.
     */
    public String getSimilarWord() {
        return (String) get(4);
    }

    /**
     * Setter for <code>rule_dict.similar_word.status</code>.
     */
    public void setStatus(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>rule_dict.similar_word.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>rule_dict.similar_word.remark</code>.
     */
    public void setRemark(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>rule_dict.similar_word.remark</code>.
     */
    public String getRemark() {
        return (String) get(6);
    }

    /**
     * Setter for <code>rule_dict.similar_word.extra_data</code>.
     */
    public void setExtraData(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>rule_dict.similar_word.extra_data</code>.
     */
    public String getExtraData() {
        return (String) get(7);
    }

    /**
     * Setter for <code>rule_dict.similar_word.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>rule_dict.similar_word.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>rule_dict.similar_word.modify_time</code>.
     */
    public void setModifyTime(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>rule_dict.similar_word.modify_time</code>.
     */
    public Timestamp getModifyTime() {
        return (Timestamp) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Long, Integer, String, String, Integer, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Long, Integer, String, String, Integer, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return SimilarWord.SIMILAR_WORD.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return SimilarWord.SIMILAR_WORD.OPERATOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return SimilarWord.SIMILAR_WORD.SOURCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SimilarWord.SIMILAR_WORD.ORIGINAL_WORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SimilarWord.SIMILAR_WORD.SIMILAR_WORD_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return SimilarWord.SIMILAR_WORD.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return SimilarWord.SIMILAR_WORD.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return SimilarWord.SIMILAR_WORD.EXTRA_DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return SimilarWord.SIMILAR_WORD.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return SimilarWord.SIMILAR_WORD.MODIFY_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getOperatorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getOriginalWord();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getSimilarWord();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getExtraData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getModifyTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getOperatorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getOriginalWord();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getSimilarWord();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getExtraData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getModifyTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SimilarWordRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SimilarWordRecord value2(Long value) {
        setOperatorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SimilarWordRecord value3(Integer value) {
        setSource(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SimilarWordRecord value4(String value) {
        setOriginalWord(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SimilarWordRecord value5(String value) {
        setSimilarWord(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SimilarWordRecord value6(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SimilarWordRecord value7(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SimilarWordRecord value8(String value) {
        setExtraData(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SimilarWordRecord value9(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SimilarWordRecord value10(Timestamp value) {
        setModifyTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SimilarWordRecord values(Long value1, Long value2, Integer value3, String value4, String value5, Integer value6, String value7, String value8, Timestamp value9, Timestamp value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SimilarWordRecord
     */
    public SimilarWordRecord() {
        super(SimilarWord.SIMILAR_WORD);
    }

    /**
     * Create a detached, initialised SimilarWordRecord
     */
    public SimilarWordRecord(Long id, Long operatorId, Integer source, String originalWord, String similarWord, Integer status, String remark, String extraData, Timestamp createTime, Timestamp modifyTime) {
        super(SimilarWord.SIMILAR_WORD);

        set(0, id);
        set(1, operatorId);
        set(2, source);
        set(3, originalWord);
        set(4, similarWord);
        set(5, status);
        set(6, remark);
        set(7, extraData);
        set(8, createTime);
        set(9, modifyTime);
    }
}
